CREATE TABLE DOCTORS (
    ID BIGINT IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    MIDDLENAME VARCHAR(255) NOT NULL,
    SPECIALIZATION VARCHAR(255)
);

CREATE TABLE PATIENTS (
    ID BIGINT IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    MIDDLENAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255)
);

CREATE TABLE prescriptions (
    ID BIGINT IDENTITY PRIMARY KEY,
    DESCRIPTION VARCHAR(512),
    DOCTORID BIGINT NOT NULL,
    PATIENTID BIGINT NOT NULL,
    START_DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL,
    PRIORITY INTEGER,
    FOREIGN KEY (DOCTORID) REFERENCES DOCTORS(id),
    FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(id)
);